apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    app: voting-app
    name: result
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      name: result
  template:
    metadata:
      labels:
        name: result
    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
