apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: voting-app
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      name: voting
  template:
    metadata:
      labels:
        name: voting
    spec:
      containers:
      - name: voting-app
        image: dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80
